/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const IssueNumberLazyImport = createFileRoute('/issue/$number')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IssueNumberLazyRoute = IssueNumberLazyImport.update({
  path: '/issue/$number',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/issue.$number.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/issue/$number': {
      id: '/issue/$number'
      path: '/issue/$number'
      fullPath: '/issue/$number'
      preLoaderRoute: typeof IssueNumberLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  IssueNumberLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/issue/$number"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/issue/$number": {
      "filePath": "issue.$number.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
